### ISSUE TITLE
IP-addresses cannot be reused.

### ISSUE THREAD

**Issue by Bearcomtech** [Microsoft/SDN#137]
Hi,
My setup has been working for some month now and all have seemed fine. Recently (I suspect after an update) the VPN functionality has stopped working. The problem seems to rely in that the load balancers do no longer announce my gateway ip over bgp. 

In VMM if I go to Fabric->Networking->Network Service and click properties on my network controller and choose Services I can now on the gateway manager role select a “Public IPv4 address”.
If I select a new address that has not been used before load balancers will start announcing the gateway ip and vpn connections work. If I change back it will stop announcing it. If I change to the new address again. It will not be announced either. I have to select a third address to make it announce my ip and to get vpn working. It seems that the addresses here cannot be used ever again with the load balancers. If I try to make a network that uses nat on one of these addresses I have used for vpn gateway ip before it will not work either.  The address seems to be forever consumed.

I have checked in vmm and there are no references to those IP-addresses I have consumed this way except for the current one set. I have also looped over every object in the network controller using the get commands found on this page https://docs.microsoft.com/en-us/powershell/module/networkcontroller/?view=win10-ps 
and there are no objects referencing addresses that have been used save for current one. 

I have tried to restart mux and gw vm’s without result. I have tried to delete and create virtual gateways and vpn connections. 

if I run Debug-NetworkControllerConfigurationState -NetworkController $ncrestendpoint -Credential $cred 
I only have the known bugs “HostNotConnectedToController” for the muxes and 2 “InfrastructurePortIsBlocked” for gateways.

My network controller Cluster version is: 10.1.1
Network controller version is: 10.1.26

Nothing seems to work to make the muxes announce my IP again. Please help me solve this problem.

**Comment by Bearcomtech** [comment]
Just some additional info.
When I logon to one of the muxes I use the tool MuxDriverControlConsole In there I can use GetMuxVipList. If the gateway has an ip that is announced it shows up in the list as a vip. But if I change back to an ip that has previous been used the vip is no longer there. It seems to me that the network controller does not update the viplist on the muxes or the muxes rejects it.

**Comment by grcusanz** [comment]
@bearcomtech  Can you confirm that your hosts, muxes and NC are all patched up to the same level?  Then, can you also configure it back to the S2S VIP with the problem and run debug-networkcontroller -NetworkController <FQDN or IP> -includeTraces:$false -Credential <pscredential> and send the resulting diagnostics-slbstateResults.Json file to sdn_feedback@microsoft.com?

**Comment by Bearcomtech** [comment]
Hi,
Thank you for looking into this matter. I have sent you the json file and some additional info regarding my current setup.

**Comment by VitCJr** [comment]
Hi, people!
It's really critical to have same level of updates on all Network Controller VMs (NC, SLB, RSGW), Hyper-V hosts and VMM. We faced it recently. 
After we updated - everything worked fine.

I can share the symptom:  if we create new VPN - it was unable to establish connections with remote endpoints. There will be a lot of 20111 RAS errors in RSGW logs 
("RoutingDomainID- {38546091-BB14-413C-AA0D-91853CE3EAF0}: A Demand Dial connection to the remote interface adb1222e-6c26-4b5c-be93-7c3cb4_4365ebe3-cd10-4749-81eb-9e2b3328fd61 on port VPN3-473 was successfully initiated but failed to complete successfully because of the  following error: The network connection between your computer and the VPN server could not be established because the remote server is not responding. This could be because one of the network devices (e.g, firewalls, NAT, routers, etc) between your computer and the remote server is not configured to allow VPN connections. Please contact your Administrator or your service provider to determine which device may be causing the problem."

**Comment by Bearcomtech** [comment]
in my case all hosts and vms are running 2017-10 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4041691)

**Comment by VitCJr** [comment]
Today we updated to KB4041688, NC version is 
NetworkControllerClusterVersion NetworkControllerVersion
------------------------------- ------------------------
10.1.1                          10.1.28

**Comment by nnamuhcs** [comment]
@VitCJr , with the latest update, is everything still fine? Thanks.

**Comment by VitCJr** [comment]
@nnamuhcs  Yep, we are still "OK" with versions:
10.1.1 10.1.28
SCVMM 2016 RU3
and KB4041688 on all infrastructure;

**Comment by nnamuhcs** [comment]
@VitCJr  Thanks for the update!

**Comment by VitCJr** [comment]
UPDATE: We installed SCVMM 2016 RU4 and WAP RU12 today.
OS and NC versions left the same.

Everything works fine in our understanding.
