### ISSUE TITLE
cannot found Get-HnsNetwork

### ISSUE THREAD

**Issue by jinxiao** [microsoft/SDN#198]
hi,all

i have installed a windows server 2016 and when i run start-kubelet.ps1 ， it happens to show no Get-HnsNetwork cmd

**Comment by adaughterson** [comment]
I'm also hitting this issue, and it appears it is because the function is not defined/exported in hns.psm1.

Additionally, there are numerous instances of something like this in the scripts:
`$na = Get-NetAdapter | ? Name -Like "vEthernet (Ethernet*"`
which is not very generic. On EC2 instances with Server 2016, the adapter names are quite different, and I've had to manually edit each of the scripts to even get to the point where start-kubelet.ps1 will fail to find Get-HnsNetwork.

Any help (even pointers to create the function myself, and submit PR) is greatly appreciated.

Adam

**Comment by lippertmarkus** [comment]
I had this problem too until switching to Windows Server 1709 (Azure)

**Comment by leezout** [comment]
Anyone have been able to run something on Server 2016 ? 
I have the exact same problem.

**Comment by adaughterson** [comment]
I switched to 1709, and all the HSN stuff is there. Would REALLY like to know how to simply make my 2016 image have all it needs to join a k8s cluster tho.

**Comment by amolsh** [comment]
I am facing exact same issue on windows 2016. "The term 'Get-HnsNetwork' is not recognized as the name of a cmdlet, function, script file, or operable program"
Does anyone able to find it's solution?

**Comment by dragon9783** [comment]
same issue on win server 2016 datacenter

**Comment by mutazn** [comment]
Make sure to use version windows server version 1709 or later, then after installing DockerMsftProvider module and Docker package, all HNS( Host Networking Service) stuff will be there (C:\Windows\System32\WindowsPowerShell\v1.0\Modules\HostNetworkingService).

PS> Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
PS> Install-Package -Name Docker -ProviderName DockerMsftProvider
PS> Restart-Computer -Force

**Comment by sammillerRLT** [comment]
Same issue, on Windows Server 2016, anyone have a solution that **isn't** "upgrade to a more recent version of Windows Server"?

**Comment by kinglionsoft** [comment]
Same issue, on Windows Server 2019.

**Comment by daschott** [comment]
Kubernetes is not supported on Windows Server 2016.

Regarding the cmdlets, you can use `Get-ContainerNetwork`, `New-ContainerNetwork`, `Remove-ContainerNetwork` on RS1 instead.
