### ISSUE TITLE
PTP on Win10 1809 - no time data available, no traffic

### ISSUE THREAD

**Issue by XPav** [Microsoft/SDN#292]
I am trying to do some simple testing with the PTP client Win 10 1809.

Setup:
0) Isolated network, with no Internet access:
1) Mac running PTPDv2 configured very simply 
```
ptpengine:interface = en0
ptpengine:preset = masterslave
```
2) 3 IP cameras, which are successfully picking up the time from ptpd
3) My Windows 10 1809 PC, with Firewall off and registry keys straight from the example txt files (VMIC and NTP disabled)

I've tried setting (and starting/stopping W32Time between each config change)
1) putting the Mac's IP address into PtpMasters
2) Setting EnableMulticastRx to 1 and leaving the Mac IP address
3) Setting EnableMulticastRx to 1 and putting the multicast group into PtpMaster

But have had no success:
```
C:\WINDOWS\system32>w32tm /resync
Sending resync command to local computer
The computer did not resync because no time data was available.
```

Using Wireshark, I see the IEEE1588 multicast broadcast traffic on the isolated network interface, but I see no traffic from the Win10 1809 PC.

**Comment by blueiso** [comment]
Same here and exactly same problem using 1809.
When running the 
``C:\WINDOWS\system32>w32tm /query /peers command
The following error occurred: Element not found. (0x80070490)``

Tested with PTPV1 and PTPV2 hardware devices from Audinate and Ravenna.

**Comment by blueiso** [comment]
Here are the logs I get where it ends in 152694 17:53:18.6501444s - W32TmServiceMain: timeout

> 152694 17:53:02.6252900s - ---------- Log File Opened -----------------
152694 17:53:02.6257352s - ReadConfig: Found provider 'NtpClient':
152694 17:53:02.6257510s - PowerNotificationCallback: Data:0 SuspendState:0
152694 17:53:02.6257850s - PowerNotificationCallback: Ignoring resume notification since we never entered suspend state.
152694 17:53:02.6258189s - ReadConfig:   'InputProvider'=0x00000001
152694 17:53:02.6258429s - ReadConfig:   'MetaDataProvider'=0x00000000
152694 17:53:02.6258657s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6258802s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6258919s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6259141s - ReadConfig: Found provider 'NtpServer':
152694 17:53:02.6259503s - ReadConfig:   'InputProvider'=0x00000000
152694 17:53:02.6259713s - ReadConfig:   'MetaDataProvider'=0x00000000
152694 17:53:02.6259923s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6260063s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6260179s - ReadConfig:   'DllName'='C:\WINDOWS\SYSTEM32\w32time.DLL'
152694 17:53:02.6260392s - ReadConfig: Found provider 'PtpClient':
152694 17:53:02.6260732s - ReadConfig:   'InputProvider'=0x00000001
152694 17:53:02.6260940s - ReadConfig:   'MetaDataProvider'=0x00000000
152694 17:53:02.6261141s - ReadConfig:   'DllName'='c:\windows\system32\ptpprov.dll'
152694 17:53:02.6261282s - ReadConfig:   'DllName'='c:\windows\system32\ptpprov.dll'
152694 17:53:02.6261398s - ReadConfig:   'DllName'='c:\windows\system32\ptpprov.dll'
152694 17:53:02.6261615s - ReadConfig: Found provider 'VMICTimeProvider':
152694 17:53:02.6262476s - ReadConfig:   'InputProvider'=0x00000001
152694 17:53:02.6262715s - ReadConfig:   'MetaDataProvider'=0x00000000
152694 17:53:02.6262942s - ReadConfig:   'DllName'='C:\WINDOWS\System32\vmictimeprovider.dll'
152694 17:53:02.6263083s - ReadConfig:   'DllName'='C:\WINDOWS\System32\vmictimeprovider.dll'
152694 17:53:02.6263201s - ReadConfig:   'DllName'='C:\WINDOWS\System32\vmictimeprovider.dll'
152694 17:53:02.6264720s - ReadConfig: 'PhaseCorrectRate'=0x00000001 (2)
152694 17:53:02.6264956s - ReadConfig: 'UpdateInterval'=0x00000064 (2)
152694 17:53:02.6265161s - ReadConfig: 'FrequencyCorrectRate'=0x00000002 (2)
152694 17:53:02.6265451s - ReadConfig: 'PollAdjustFactor'=0x00000005 (2)
152694 17:53:02.6265670s - ReadConfig: 'LargePhaseOffset'=0x02FAF080 (2)
152694 17:53:02.6265875s - ReadConfig: 'SpikeWatchPeriod'=0x00000384 (2)
152694 17:53:02.6266080s - ReadConfig: 'HoldPeriod'=0x00000005 (2)
152694 17:53:02.6266289s - ReadConfig: 'MinPollInterval'=0x00000006 (2)
152694 17:53:02.6266498s - ReadConfig: 'MaxPollInterval'=0x00000006 (2)
152694 17:53:02.6266713s - ReadConfig: 'ClockHoldoverPeriod'=0x0000C350 (2)
152694 17:53:02.6266924s - ReadConfig: 'AnnounceFlags'=0x00000005 (2)
152694 17:53:02.6267129s - ReadConfig: 'LocalClockDispersion'=0x0000000A (2)
152694 17:53:02.6267339s - ReadConfig: 'MaxNegPhaseCorrection'=0x0000D2F0 (2)
152694 17:53:02.6267552s - ReadConfig: 'MaxPosPhaseCorrection'=0x0000D2F0 (2)
152694 17:53:02.6267756s - ReadConfig: 'EventLogFlags'=0x00000002 (2)
152694 17:53:02.6267968s - ReadConfig: 'MaxAllowedPhaseOffset'=0x00000001 (2)
152694 17:53:02.6268175s - ReadConfig: 'UtilizeSslTimeData'=0x00000001 (2)
152694 17:53:02.6268383s - ReadConfig: 'ClockAdjustmentAuditLimit'=0x00000320 (2)
152694 17:53:02.6268589s - ReadConfig: 'TimeJumpAuditOffset'=0x00007080 (2)
152694 17:53:02.6268808s - Clock adjustment info: dwCurrentSecPerTick: 156250 dwDefaultSecPerTick: 156250 bSyncToCmosDisabled:1
152694 17:53:02.6269289s - PerfFreq:10000000c/s
152694 17:53:02.6269455s - currAdj:10000000 Incr:10000000 IncrEnabled:1
152694 17:53:02.6270448s - eLSState changed. Old State:0. New State:1
152694 17:53:02.6270912s - lastClockRate=156250, clockFrequency:10000000 clockPrecision=-23
152694 17:53:02.6271514s - SetTimeSlipNotification succeeds with 0x00000000.
152694 17:53:02.6297582s - W32TmServiceMain: RequestNetTopoChangeNotification Succeed
152694 17:53:02.6301729s - W32TmServiceMain: RequestNetTopoChangeNotification Succeed
152694 17:53:02.6313376s -   DomainHierarchy: LSA role change notification. Redetecting.
152694 17:53:02.6328982s - ClockDisciplineThread: Starting: SetUnsync: LI:0 S:1 RDl:0 RDs:100000000 TSF:0x0  LastUTC:4233749
152694 17:53:02.6332056s - ClockDispln: we're a reliable time service with no time source: LS: 0, : 864000000000, WAIT: 86400000
152694 17:53:02.6332197s - W32time perf counters Initialized
152694 17:53:02.6332418s - Starting Providers.
152694 17:53:02.6332552s - Starting 'PtpClient', dll:'c:\windows\system32\ptpprov.dll'
152694 17:53:02.6341251s - LoadLibrary
152694 17:53:02.6486720s - Logging Info: Time provider 'PtpClient' has started successfully
152694 17:53:02.6486972s - Successfully started 1 providers.
152694 17:53:02.6487147s - /--TimeProvider: All providers started
152694 17:53:02.6487283s - | Name:PtpClient, Started:1, Input:1, Marked:0, RefCount:0, DllName:c:\windows\system32\ptpprov.dll
152694 17:53:02.6487399s - >--
152694 17:53:02.6487513s - | Total:1, Input: 1, Marked: 0
152694 17:53:02.6487622s - \--
152694 17:53:02.6500454s - UpdateTimerQueue1: TN:661523430000::: LRT:0  LUT:661523280000 LAFLTNS:0 TSLGT:0 LTNS:864000000000
152694 17:53:02.6500648s - W32TmServiceMain: waiting i16.000s (64.000s)
152694 17:53:02.6502383s - RPC Call - Query Configuration
152694 17:53:02.6502579s - RPC Call - Query Provider Configuration
152694 17:53:02.6502747s - RPC Call - Query Provider Configuration
152694 17:53:02.6502878s - RPC Call - Query Provider Configuration
152694 17:53:02.6503036s - RPC Call - Query Provider Configuration
152694 17:53:02.6506867s - W32TmServiceMain: Network Topology Change
152694 17:53:02.6507224s - UpdateTimerQueue1: TN:661523430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:0 TSLGT:6056 LTNS:864000000000
152694 17:53:02.6507378s - W32TmServiceMain: waiting i15.999s (63.999s)
152694 17:53:02.6507720s - W32TmServiceMain: RequestNetTopoChangeNotification Succeed
152694 17:53:02.6508029s - W32TmServiceMain: Network Topology Change
152694 17:53:02.6508284s - UpdateTimerQueue1: TN:661523430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:0 TSLGT:6539 LTNS:864000000000
152694 17:53:02.6508420s - W32TmServiceMain: waiting i15.999s (63.999s)
152694 17:53:02.6508734s - W32TmServiceMain: RequestNetTopoChangeNotification Succeed
152694 17:53:04.3366394s - RPC Caller is NT VIRTUAL MACHINE\9DF0E83B-47BC-4FA2-8E59-D21D0F4E1F69 (S-1-5-83-1-2649811003-1336035260-500324750-1763659279)
152694 17:53:04.3366785s - RPC Call Attribute is local=1, kernel=0, session=0, authentication=6, protocol=2, OpNum=6
152694 17:53:04.3367166s - RPC Call - Query Status
152694 17:53:04.6239004s - W32TimeHandler called: SERVICE_CONTROL_INTERROGATE
152694 17:53:09.3379949s - RPC Call - Query Status
152694 17:53:14.3380801s - RPC Call - Query Status
152694 17:53:18.6501444s - W32TmServiceMain: timeout
152694 17:53:18.6501915s - UpdateTimerQueue1: TN:661683430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:159999774 TSLGT:159999774 LTNS:864000000000
152694 17:53:18.6502056s - W32TmServiceMain: waiting 64.000s
152694 17:53:19.3382928s - RPC Call - Query Status
152694 17:53:24.3399635s - RPC Call - Query Status
152694 17:53:29.3411139s - RPC Call - Query Status
152694 17:53:34.3411663s - RPC Call - Query Status
152694 17:53:39.3421269s - RPC Call - Query Status
152694 17:53:44.3428069s - RPC Call - Query Status
152694 17:53:49.3438313s - RPC Call - Query Status
152694 17:53:54.3439444s - RPC Call - Query Status
152694 17:53:59.3457909s - RPC Call - Query Status
152694 17:54:04.3478102s - RPC Call - Query Status
152694 17:54:09.3477880s - RPC Call - Query Status
152694 17:54:14.3487880s - RPC Call - Query Status
152694 17:54:19.3497877s - RPC Call - Query Status
152694 17:54:22.6504436s - W32TmServiceMain: timeout
152694 17:54:22.6504947s - UpdateTimerQueue1: TN:662323430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:800000000 TSLGT:800002425 LTNS:864000000000
152694 17:54:22.6505148s - W32TmServiceMain: waiting 64.000s
152694 17:54:24.3497709s - RPC Call - Query Status
152694 17:54:29.3508564s - RPC Call - Query Status
152694 17:54:34.3526181s - RPC Call - Query Status
152694 17:54:39.3538373s - RPC Call - Query Status
152694 17:54:44.3548071s - RPC Call - Query Status
152694 17:54:49.3558064s - RPC Call - Query Status
152694 17:54:54.3567977s - RPC Call - Query Status
152694 17:54:59.3567825s - RPC Call - Query Status
152694 17:55:04.3567994s - RPC Call - Query Status
152694 17:55:09.3568019s - RPC Call - Query Status
152694 17:55:14.3577711s - RPC Call - Query Status
152694 17:55:19.3578169s - RPC Call - Query Status
152694 17:55:24.3579267s - RPC Call - Query Status
152694 17:55:26.6505813s - W32TmServiceMain: timeout
152694 17:55:26.6506340s - UpdateTimerQueue1: TN:662963430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:1440000000 TSLGT:1440003302 LTNS:864000000000
152694 17:55:26.6506596s - W32TmServiceMain: waiting 64.000s
152694 17:55:29.3590397s - RPC Call - Query Status
152694 17:55:34.3597703s - RPC Call - Query Status
152694 17:55:39.3599805s - RPC Call - Query Status
152694 17:55:44.3600880s - RPC Call - Query Status
152694 17:55:49.3606221s - RPC Call - Query Status
152694 17:55:54.3612401s - RPC Call - Query Status
152694 17:55:59.3619870s - RPC Call - Query Status
152694 17:56:04.3625729s - RPC Call - Query Status
152694 17:56:09.3626235s - RPC Call - Query Status
152694 17:56:14.3632535s - RPC Call - Query Status
152694 17:56:19.3632662s - RPC Call - Query Status
152694 17:56:24.3633649s - RPC Call - Query Status
152694 17:56:29.3634301s - RPC Call - Query Status
152694 17:56:30.6510669s - W32TmServiceMain: timeout
152694 17:56:30.6511002s - UpdateTimerQueue1: TN:663603430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:2080000000 TSLGT:2080007413 LTNS:864000000000
152694 17:56:30.6511136s - W32TmServiceMain: waiting 64.000s
152694 17:56:34.3634838s - RPC Call - Query Status
152694 17:56:39.3635352s - RPC Call - Query Status
152694 17:56:44.3636012s - RPC Call - Query Status
152694 17:56:49.3645915s - RPC Call - Query Status
152694 17:56:54.3655514s - RPC Call - Query Status
152694 17:56:59.3656373s - RPC Call - Query Status
152694 17:57:04.3656052s - RPC Call - Query Status
152694 17:57:09.3656546s - RPC Call - Query Status
152694 17:57:14.3657282s - RPC Call - Query Status
152694 17:57:19.3666411s - RPC Call - Query Status
152694 17:57:24.3674623s - RPC Call - Query Status
152694 17:57:29.3688193s - RPC Call - Query Status
152694 17:57:34.3695308s - RPC Call - Query Status
152694 17:57:34.6511641s - W32TmServiceMain: timeout
152694 17:57:34.6512036s - UpdateTimerQueue1: TN:664243430000::: LRT:661523430000  LUT:661523280000 LAFLTNS:2720000000 TSLGT:2720008119 LTNS:864000000000
152694 17:57:34.6512171s - W32TmServiceMain: waiting 64.000s
152694 17:57:39.3696101s - RPC Call - Query Status

**Comment by JhoeyPTP** [comment]
Im getting the same error when running the command: w32tm /query /peers  and w32tm /resync
Did any of you find something out?

**Comment by dcuomo** [comment]
w32tm /query /peers is a typo in the doc and is not expected to work with the PTP Client.  Apologize for the confusion.

Please check that you're seeing communication on the Windows 10 Client on ports 319 and 320.  

Please also verify that the Announce message from the grandmaster is non-zero for the PTP_TIMESCALE and PTP_UTC_REASONABLE flags.

**Comment by blueiso** [comment]
JhoeyPTP, did not find a solution.
dcuomo, yes I could receive on 319 and 320 and can see the packets in Wireshark for Sync, Follow_Up, Delay...
I don't get Announce messages. Here is what the Sync Packets look like.

![image](https://user-images.githubusercontent.com/7450864/54712844-b559a380-4b23-11e9-9c84-06367dba4dfd.png)

**Comment by dcuomo** [comment]
@blueiso - We only support 1588v2.  versionPTP: must be 2

Once testing with the correct GM version, check your announce flags as previously mentioned.

Thanks for giving this a shot!

**Comment by JhoeyPTP** [comment]
We got ptp working. We ran into with issue where the Windows clock is 37 secounds faster though. If i set the master clock to 14:00:00, the Windows clock is set to 13:59:23 pluss the time is takes to set the slave. I dont know if this is a typical problem, or if this is a paramter problem in w32time registry. The other slaves is synchronized correctly.

If i look away from the 37secounds "offset" the only synchronzing error is the network delay.

We got it working and thanks for all the help. Dont worry if you cant help me on this problem with the information you have. You have done enough.
________________________________

**Comment by jake8125** [comment]
same issue as OP, running win server 2019 and unable to see any packets on wireshark when attempting resync.
Have tried all same steps also. @JhoeyPTP what was your solution when you finally got it working?
Thanks for any help, really hoping to get this working

**Comment by dcuomo** [comment]
@JhoeyPTP - 37 seconds is the number of seconds offset of UTC from TAI.  This is the sum total of leap seconds added to UTC (27 + 10 initial correction).  I'm wondering if there is something strange about the PTP timescale chosen by the grandmaster?

@jake8125 - If you're not seeing PTP packets (UDP 319 and 320) then this is not a problem with the PTP Provider.  It is likely the Windows firewall or another problem preventing the system from seeing the packets (this could be a windows or grandmaster issue).  

We have published our PTPd configuration examples to help customers get started: https://github.com/Microsoft/SDN/tree/master/Time/PTP

Please also check the Time-Service-PTP-Provider/Operational log for indications as to why it may not be synchronizing

**Comment by JhoeyPTP** [comment]
I had multiple problems. One of them being Firewall, but also my Linux cards that I use for PTP wasn’t plug and play with windows. With each other PTP runs without any setup, but with a Windows PC in the system I needed to specify that the master was the master cause it diddnt run the BMC against the Windows PC. There where also some errors in the guides that mislead me, but that’s corrected now.

________________________________

**Comment by dcuomo** [comment]
Sorry about the errors.  Glad we corrected them now.  We added some troubleshooting to the guide as well.

We do not accept arbitrary timescales which is often a challenge with software grandmasters (e.g. ptp4l announces an arbitrary timescale when not using hardware timestamping).

Are the issues here now closed?  Can we close this?

**Comment by JhoeyPTP** [comment]
Yes, i dont have issues anymore.
Thanks

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by XPav** [comment]
Can I get a little more information on multicast Rx?  When enabled, should PtpMasters be the Multicast Address (224.0.1.129) or remain the address of the timeserver?

My announce flags are also wrong, but that's my problem.

**Comment by JhoeyPTP** [comment]
Ptpmasters should be your grandmaster not the muliticast group. My ptpmasters is 192.168.126.xxx. atleast that worked for me.

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jake8125** [comment]
I'm assuming windows isn't happy with the grandmasters i'm using (an oscilloquartz 5401 and 5410) but finding it hard to troubleshoot without being able to see the packets. turned my firewall off and still nothing showing up in wireshark. Even if the grandmaster is not responding, would I expect to see a ptp packet out of the interface?

**Comment by XPav** [comment]
With the troubleshooting information added next week and the comments that some people have gotten it working, I will close this issue.

**Comment by AndreV84** [comment]
hey guys;
winddows registry doesn't seem to have PTP tree
shall I create it manually or there is a user friendly step to upload ptp configuration somehow?

**Comment by AndreV84** [comment]
winver 1909

**Comment by AndreV84** [comment]
with ptp TIMESCALE true & ptp utc reasonable  true;
it wont resync on windows client;
what is the reason? intervals? which intervals?

**Comment by rodiers** [comment]
Here same problem.
I see Announce Messages, Follow_Up messages and Sync messages at client side
For example:
4839	190.165019	146.122.36.248	10.146.251.160	PTPv2	106	Announce Message
Frame 4839: 106 bytes on wire (848 bits), 106 bytes captured (848 bits) on interface \Device\NPF_{3E540252-158A-4F20-8E06-68316A131D10}, id 0
Ethernet II, Src: 02:00:0a:92:fb:a0 (02:00:0a:92:fb:a0), Dst: MS-NLB-PhysServer-05_85:7f:eb:80 (02:05:85:7f:eb:80)
Internet Protocol Version 4, Src: 146.122.36.248, Dst: 10.146.251.160
User Datagram Protocol, Src Port: 62870, Dst Port: 320
Precision Time Protocol (IEEE1588)
    0000 .... = transportSpecific: 0x0
    .... 1011 = messageId: Announce Message (0xb)
    0000 .... = Reserved: 0
    .... 0010 = versionPTP: 2
    messageLength: 64
    subdomainNumber: 0
    Reserved: 0
    flags: 0x040c
        0... .... .... .... = PTP_SECURITY: False
        .0.. .... .... .... = PTP profile Specific 2: False
        ..0. .... .... .... = PTP profile Specific 1: False
        .... .1.. .... .... = PTP_UNICAST: True
        .... ..0. .... .... = PTP_TWO_STEP: False
        .... ...0 .... .... = PTP_ALTERNATE_MASTER: False
        .... .... ..0. .... = FREQUENCY_TRACEABLE: False
        .... .... ...0 .... = TIME_TRACEABLE: False
        .... .... .... 1... = PTP_TIMESCALE: True
        .... .... .... .1.. = PTP_UTC_REASONABLE: True
        .... .... .... ..0. = PTP_LI_59: False
        .... .... .... ...0 = PTP_LI_61: False
    correction: 0.000000 nanoseconds
    Reserved: 0
    ClockIdentity: 0x00155dfffe0de79e
    SourcePortID: 1
    sequenceId: 30
    control: Other Message (5)
    logMessagePeriod: 127
    originTimestamp (seconds): 0
    originTimestamp (nanoseconds): 0
    originCurrentUTCOffset: 37
    priority1: 120
    grandmasterClockClass: 10
    grandmasterClockAccuracy: The time is accurate to within 1 us (0x23)
    grandmasterClockVariance: 28768
    priority2: 125
    grandmasterClockIdentity: 0x00155dfffe0de79e
    localStepsRemoved: 0
    TimeSource: INTERNAL_OSCILLATOR (0xa0)

In the registry at client side I have:
PtpMasters 146.122.36.248 192.168.83.141
All other registry keys are from https://github.com/microsoft/W32Time/blob/master/Precision%20Time%20Protocol/Windows%20Configuration%20Helpers/PTPClientConfig.txt

I restarted the service and ran w32tm /config /update

and I get these results for different commands:

w32tm /query /configuration
[Configuration]

EventLogFlags: 2 (Local)
AnnounceFlags: 0 (Local)
TimeJumpAuditOffset: 28800 (Local)
MinPollInterval: 10 (Local)
MaxPollInterval: 15 (Local)
MaxNegPhaseCorrection: 4294967295 (Local)
MaxPosPhaseCorrection: 4294967295 (Local)
MaxAllowedPhaseOffset: 300 (Local)

FrequencyCorrectRate: 4 (Local)
PollAdjustFactor: 5 (Local)
LargePhaseOffset: 50000000 (Local)
SpikeWatchPeriod: 900 (Local)
LocalClockDispersion: 10 (Local)
HoldPeriod: 5 (Local)
PhaseCorrectRate: 1 (Local)
UpdateInterval: 30000 (Local)


[TimeProviders]

PtpClient (Local)
DllName: c:\windows\system32\ptpprov.dll (Local)
Enabled: 1 (Local)
InputProvider: 1 (Local)

Windows Time Agent (Local)
DllName: w32tmdt.cpl (Local)
Enabled: 1 (Local)
InputProvider: 0 (Local)

NtpClient (Local)
DllName: C:\WINDOWS\system32\w32time.dll (Local)
Enabled: 0 (Local)
InputProvider: 0 (Local)

NtpServer (Local)
DllName: C:\WINDOWS\system32\w32time.dll (Local)
Enabled: 0 (Local)
InputProvider: 0 (Local)

VMICTimeProvider (Local)
DllName: C:\WINDOWS\System32\vmictimeprovider.dll (Local)
Enabled: 0 (Local)
InputProvider: 1 (Local)

w32tm /resync
Sending resync command to local computer
The computer did not resync because no time data was available.

w32tm /query /status /verbose
Leap Indicator: 3(not synchronized)
Stratum: 0 (unspecified)
Precision: -23 (119.209ns per tick)
Root Delay: 0.0000000s
Root Dispersion: 0.0000000s
ReferenceId: 0x00000000 (unspecified)
Last Successful Sync Time: unspecified
Source: Local CMOS Clock
Poll Interval: 10 (1024s)

Phase Offset: 0.0000000s
ClockRate: 0.0156250s
State Machine: 0 (Unset)
Time Source Flags: 0 (None)
Server Role: 0 (None)
Last Sync Error: 1 (The computer did not resync because no time data was available.)
Time since Last Good Sync Time: 332.5131215s

**Comment by JackGarbiec** [comment]
To anyone struggling with getting multicast working, you might need to add the following reg key
`ChosenMcastIfIpAddr:IP_OF_YOUR_INTERFACE`. I was finally able to see ptp traffic once that was added, setting EnableMulticastRx to 1 wasn't enough, it was for some reason trying to join the multicast group on loopback interface. This issue might only be present if you've more than one NIC.
