### ISSUE TITLE
Kubernetes on windows - register.ps1 vs start.ps1

### ISSUE THREAD

**Issue by blakeja** [Microsoft/SDN#332]
I was hoping to get some clarification on properly setting up the Kubernetes windows services using register.ps1, in my case using l2bridge.  The script itself is pretty straightforward and "works" out of the gate.  But when you compare the startup workflow of start.ps1 to the logic in register.ps1, there are some discrepancies.

The are two places the scripts diverge.

First, in Start.ps1, the StartFlannelD function is called from helper.psm1, which in turn calls the CleanupOldNetwork function.  Compare this to the register.ps1 setup, here CleanupOldNetwork would never be called as nssm simple starts the flanneld executable.  Is the CleanupOldNetwork function required for each restart of flanneld or should this only be called one time during the initial setup?

Second, in Start-Kubeproxy.ps1 "Get-HnsPolicyList | Remove-HnsPolicyList" is called prior to starting kube-proxy.exe.  Register.ps1 does not provide this call, so this would never be executed when restarting the kube-proxy windows service.

Any help / guidance would be appreciated.  I fairly certain that skipping one or both of these calls (cleaning up the network and resetting the hns policy list) results in kube-proxy not working after one or more service restarts.  I've resorted to running start.ps1 at the moment, but I would prefer to use windows services.

**Comment by daschott** [comment]
register-svc.ps1 assumes you have called at least install.ps1 previously and registered your node. You should only have to call register-svc.ps1 once and shouldn't have to cleanup networking after service restart, as this could delete active endpoints.

Can you check whether the problem is perhaps that the other services launch prematurely before flannelD? I think we should make kubelet depend on flannelD so that they all launch in the right order: flannelD -> kubelet -> kube-proxy -- I'll try to investigate this when I have time, but can you try it? `.\nssm.exe set $KubeletSvc DependOnService $FlanneldSvc`

**Comment by blakeja** [comment]
I set kubelet to be

**Comment by blakeja** [comment]
Using l2bridge mode, kubernetes v1.13.4, flanneld v0.11.0.

**Comment by blakeja** [comment]
Dug in a bit deeper, the issue was on my end, kind of.  At some point I had to go in and change all the default values for $InterfaceName in start.ps1, install.ps1 and helper.psm1 to the correct interface on a per server basis.  I had missed two of the five instances of this.  Fixed this, re-ran start.ps1, closed out the windows, restarted the services and everything seems to be working as expected.
