### ISSUE TITLE
GW do not connect to Transit network

### ISSUE THREAD

**Issue by AlexisLessard** [Microsoft/SDN#36]
I deployed NC with the VMM templates, as well as the SLB MUX, but I've had issues with the gw template. Most notably, while all my VM's connected to the Transit and management network, they didn'T connect to the backend network. I'll try connecting it manually, but that didn't happen with the slb template. Everything onboarded as planned, but that's not the case with the GW template. Have you seen this in other tests?

**Comment by JMesser81** [comment]
I haven't noticed this myself. Any ideas @RamanDhillon

**Comment by RamanDhillon** [comment]
Alexis, that is the design :) The backend NIC is on HNV PA network but it is the virtualized NIC, so it won't have any one IP Address (it'll show an IP address in 169 network). Because the GW VMs are multitenant, each tenant compartment will have a corresponding virtual NIC with a CA space IP Address as and when the tenants are configured.
Please refer to [this blog ](https://blogs.technet.microsoft.com/networking/2013/09/28/multi-tenant-site-to-site-s2s-vpn-gateway-with-windows-server-2012-r2/) for more information on Multitenant stack and HNV Gateways. Let me know if your problem is different.

**Comment by AlexisLessard** [comment]
No it's not different. I'm able to ping my transit NIC so I guess they are connected, even tough it's not visible in the VMM consoles. The NIC are connected to the virtual switchs inside the hosts tough. So yeah the VMM templates seems to work fine. Most of the errors I had were human errors and details I forgot to enter.
