### ISSUE TITLE
NC Host Agent not starting

### ISSUE THREAD

**Issue by benpiper** [Microsoft/SDN#51]
SDNexpress.ps1 fails with the following error:

```
Failed to start service 'NC Host Agent (NCHostAgent)'.
At C:\sdnexpress\scripts\SDNExpress.ps1:3283 char:9
+         Start-DscConfiguration -Path .\ConfigureHostNetworkingPreNCSe ...
```

The system event log shows the following error:
`The NC Host Agent service terminated with the following error: 
A device attached to the system is not functioning.`

**Comment by nwoodmsft** [comment]
Hi Ben, I think I saw this one time, but haven't been able to repro since....it seems to be related to clean-up/undo and the ovsdb conf file ending up with a corrupted copy. First to confirm, had you previously run SDNExpressUndo.ps1 against this system?

**Comment by benpiper** [comment]
Yes, several times.

**Comment by nwoodmsft** [comment]
Thanks, it's probably the corruption issue which I mentioned or a case of the .conf files in your SDNExpress\AgentConf being mismatched with the OS. Either way, the 'undo' script shouldn't really be cleaning up by replacing those files (that will be resolved shortly). 

Aside from starting with a fresh host, the only workaround I am aware of is to make sure NcHostAgent service really is stopped and then navigate to C:\ProgramData\Microsoft\Windows\NcHostAgent and replace the Firewall.conf and ServiceInsertion.conf files with fresh copies from GitHub (https://github.com/Microsoft/SDN/tree/master/SDNExpress/AgentConf). You may already have these files locally from when you downloaded SDNExpress (they are in the AgentConf) directory) but given that you are seeing corruption/mismatch I think it would be a good idea to re-download those files from the SDN Master branch (i'm assuming that you are working on Server 2016 RTM and not earlier preview builds).

**Comment by benpiper** [comment]
Thanks, I'll try that. I've rebuilt the host since then and am actually having a different issue with the script not provisioning the infrastructure VMs. I get a "Windows could not complete the installation" error. It only happens when using the script. Just booting the sysprepped master VHDX works. Is there something special the VHDX needs for the script to provision the VMs?

**Comment by nwoodmsft** [comment]
Hi Ben, Nothing special, no. The script creates a unattend file and copies it into the root of the VHDX so that on first boot the VM will come up with the right domain membership and management IP plumbed etc. I've not seen any reports of problems with infra VMs booting, so I would suspect an issue with the sysprep'd VHDX. When you syspre'd it, did you select both /oobe and /generalize ?

**Comment by benpiper** [comment]
I resolved the issue with the VHDX. But after rebuilding the host and copying the Firewall.conf and ServiceInsertion.conf files, I'm still getting the Failed to start service 'NC Host Agent (NCHostAgent)` error. The event log shows the same `A device attached to the system is not functioning` error even though it doesn't specify which device.

**Comment by nwoodmsft** [comment]
Hi Ben, Thanks for trying that. Given that this is consistent I'm wondering if the .conf files are somehow mismatched to your build. Can you confirm which version of Windows Server 2016 you are running on the hosts? The .conf files from the Master fork of this GitHub repro is intended to be aligned with Windows Server 2016 RTM or later. If your build is RTM and your using the latest .conf files from Master, then the issue should not reproduce (but if the build is TP5 or the .conf files were from an earlier version of SDNExpress then you would see this issue).

Also, replacing the .conf files is not a required step...it's just intended to be a last resort clean-up step that the SDNExpressUndo.ps1 script performs to ensure that no tenant policies (e.g. firewall rules) are left behind when you undo the SDN fabric. If this step is the only thing causing problems for your environment, then it would be safe to just comment out the RestoreOVSDBConfFiles script block within SDNExpressUndo.ps1 to unblock yourself and ensure that this conf files don't get copied in future. 

To fix your current environment, you can either copy the .conf files from another host which is healthy (i.e. nchostagent is able to start on the host) or reimage the host so that it starts with a clean/fresh .conf

**Comment by benpiper** [comment]
I started over fresh with a clean install of RTM and the problem with the NC host agent is resolved. It seems that running the SDNExpress script unsuccessfully breaks something. If the first run is successful, then the NC host agent starts.
