### ISSUE TITLE
"IPAddress not in the correct format" when using an IPv6 subnets with SDNExpressTenant.ps1

### ISSUE THREAD

**Issue by benpiper** [Microsoft/SDN#59]
When running SDNExpressTenant.ps1 with the config file populated with IPv6 subnets, I get the following error:
```

VERBOSE: [HYPERV1]:                            [[Script]CreateVNet] Invoke-WebRequestWithRetries: Put Exception: {
  "error": {
    "code": "InvalidIPAddress",
    "message": "IPAddress 2001:90::/64 is not in the correct format.",
    "innerError": "Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.ValidationException: IPAddress 2001:90::/64 is not in the correct format.
```

**Comment by nwoodmsft** [comment]
Hi Ben,

Please see the "Unsupported Network Scenarios" section of the following article: https://technet.microsoft.com/en-us/windows-server-docs/networking/windows-server-2016-supported-networking-scenarios

For Server 2016, IPv6 is not supported in either the underlay or overlay. Please use a IPv4 subnet for your tenant virtual network.

I'll keep this issue open so that we can add a simple check in the scripts to detect IPv6 addresses in the config files and display a friendlier message.

Thanks!
-Nick
