### ISSUE TITLE
VMMExpress - Deployed VMs for NC,SLB and GW are not Highly Available

### ISSUE THREAD

**Issue by slavizh** [Microsoft/SDN#67]
Probably it is good idea all the hardware configurations for the VMs in the templates to be highly available. That way when deployment is done the VMs deployed will be highly available.

**Comment by JMesser81** [comment]
@manishmsft - 

Not sure what you mean by this, @slavizh. The Network Controller, SLB, and Gateways are already Highly-Available when using the "production" templates. 

We use a clustering technology called Service Fabric to guarantee NC is highly-available.

The SLB Muxes are stateless and we use BGP Dynamic Routing updates to advertise routes for the VIPs through the muxes. We also use ECMP spreading for redundancy so that multiple SLB Muxes can advertise different routes (with the same metric) for the VIPs. 

The Gateways are highly-available based on Control-plane updates and health checks.

**Comment by slavizh** [comment]
In the service Templates for the HW configuration none of them are marked as highly available. This is VMM term so when you deploy a VM it will be deployed on a Hyper-V cluster and on a storage that is shared between the hosts (example C:\ClusterStorage\Volume1 or SMB share) If that checkbox is not checked the VMs could be deployed on a local storage (for example something like C:\ or D:\ and etc.)
In the xml file this is the option `<vmmst:HighlyAvailable>false</vmmst:HighlyAvailable>` I think it will be better if all templates are `<vmmst:HighlyAvailable>true</vmmst:HighlyAvailable>`.
Let me know if this makes sense now.

**Comment by sanjkum** [comment]
It would not be a good idea to keep the template default to deploy highly available VMs, as it will break the deployment in non clustered host environment . Next update of VMMExpress will expose a new parameter "HighlyAvailableVMs" which should be set to $true in order to deploy VMs on clustered Hosts.

**Comment by slavizh** [comment]
Great! That is solution as well. I will close the issue than since you've planned that.
