### ISSUE TITLE
KB4010672 Breaks all new networks

### ISSUE THREAD

**Issue by Bearcomtech** [Microsoft/SDN#86]
Soo. I had almost everything setup. Just had my gateways left do deploy. And I faced the issue here that some other people have had. To this the solution was to install KB4010672 on the network controllers and reboot them twice. It all seems perfect in the beginning and the gateways can be deployed. 

Now the real hell starts. If you create any new vm’s or vmnetworks nothing works. All configurations get the error PolicyConfigurationFailure. So, my thought was to install this patch everywhere. All my hosts and vm’s now have this patch but I still faced the same error. 

My next step was to redeploy everything fresh with this patch from the beginning (including KB4013429). I had a fresh vmm (UR2.1) and fresh hosts with this patch. My image for the sdn deployment also had this patch. Now everything works perfectly and network controllers got deployed and no errors show up. Now I deploy my HNV network and all seams fine. I deploy a test vmnetwork with ip pool and creates a virtual machine on top of this.  This is where I get PolicyConfigurationFailure again. 

This patch breaks communication between hosts and network controllers. I have PACA mappings and they have established states on port 6640. But the policys do not get pushed to the hosts.

Does anyone know how to solve this issue?

Here is my output from Debug-NetworkControllerConfigurationState

Checking Network Controller for any Configuration State Errors...
Fetching ResourceType:     accessControlLists
Fetching ResourceType:     servers

---------------------------------------------------------------------------------------------------------
ResourcePath:     https://ncc01.mydomain.com/Networking/v1/servers/00000000-0000-0000-0000-0cc47a6eea42
Status:           Warning

Source:           VirtualNetwork
Code:             PolicyConfigurationFailure
Message:          Failed to configure the policies on the host device.

----------------------------------------------------------------------------------------------------------

Fetching ResourceType:     virtualNetworks

---------------------------------------------------------------------------------------------------------

ResourcePath:     https://ncc01.mydomain.com/Networking/v1/virtualNetworks/00377689-bdb5-4bf6-85a0-b16dad107469
Status:           Failure

----------------------------------------------------------------------------------------------------------

Fetching ResourceType:     networkInterfaces

--------------------------------------------------------------------------------------------------------

ResourcePath:     https://ncc01.mydomain.com/Networking/v1/networkInterfaces/079ecf8c-7f86-466b-89f3-1731af29de3f
Status:           Failure

Source:           VirtualSwitch
Code:             PolicyConfigurationFailure
Message:          Failed to configure the policies on the host device.
Source:           VirtualNetwork
Code:             PolicyConfigurationFailure
Message:          Failed to configure the policies on the host device.

----------------------------------------------------------------------------------------------------------
Fetching ResourceType:     virtualGateways
Fetching ResourceType:     loadbalancerMuxes
Fetching ResourceType:     Gateways

--------------------------------------------------------------------------------------------------------

Here is an error from the networkconttroller-VSwitchService
Goal State push on device failed: 15444805-6dc7-4a01-8b02-b78b334679a7, Error: TimedOut

**Comment by kallie-b** [comment]
@Bearcomtech--I'm sorry you're experiencing this issue, and thanks for reaching out. I'll follow up with my team and we'll get back to you on this ASAP.

**Comment by grcusanz** [comment]
This issue is caused by VMM when this update installs a new certificate on the host without updating the network controller.  The simple solution is to use VMM to "Repair" each host.  That will cause VMM to import the correct certificate into the network controller.  The VMM team is looking into addressing this to keep it from occurring with future updates.

**Comment by Bearcomtech** [comment]
@kallie-b Thank you for looking into this.

@grcusanz Could you elaborate a bit more? which certificate is the problem? In my tests i installed everything for the begining with all the latest patches which should make all involved systems to have all certificates from the begining. Except for my selfsigned certificate which is deplyoed during controller deplyment. I even in my first test removed the Switch from the host and reattached it without success.

**Comment by kallie-b** [comment]
Ping @grcusanz

**Comment by micros01** [comment]
We had similar issue, it turned out to be the scvmm certificate that was missing from trusted root on the Hyper-V hosts, it was just present in the personal store. Could be worth a look.

**Comment by Bearcomtech** [comment]
I am still confured. I got it working by installing hosts without updates and the rest of SDN components with fully updated vm's. I still get ALOT of errors when i run my debug but everything seems to work. however i would like to be able to patch my hyper-v hosts. Which is the scvmm certificate? which certificate is it that i need to verify. My selfsigned certificate is located on all hosts under hklm\root but you mention some other certificate that i cannot seem to understand which it is.

**Comment by micros01** [comment]
Hi, I meant the cert with friendly name "SCVMM_CERTIFICATE_KEY_CONTAINERhostname.domainname"
We have been troubleshooting this with Microsoft and at first that seemed to be the problem.
This however wasnt the issue.

The problem we had was caused by another certificate in "Trusted Root"(on all Hyper-V hosts), it was a cert that was  "issued by" "Verisign Class 3 Public Primary Certification Authority" and "Issued to" "VeriSign Class 3 Public Primary Certification Authority - G5". 
According to Microsoft this cert should not be in the "Trusted Root" since "Issued By" and "Issued To" is different. 

This certificate was most likely automatically installed when we installed hardware agents, raid management or some other Fujitsu specific software. We don't at this point know for sure wich part installed this.

To solve this, rightclick the "bad" cert -> Properties and change "Certificate Purposes" to "Disable all" and after that restart the NC Host agent on the host.

This solved our issue, hopefully it will help someone else.
All credits to find the problem goes to Microsofts SDN/VMM team that helped us solve this.

**Comment by JMesser81** [comment]
Okay to close?

**Comment by JMesser81** [comment]
@Bearcomtech okay to close? Did this solve your issue?

**Comment by Bearcomtech** [comment]
Hi,
Well i have not solved the issue yet.  But i suppose you can close the ticket. My problem does not seem to occur due to certificates.
